### ISSUE TITLE
Importing photos from Android also imports thumbnails.

### ISSUE THREAD

**Issue by Schykle** [elementary/photos#553] opened 2020-02-20 03:08 UTC
## Describe the bug
Importing from an Android phone also imports thumbnails from the `.thumbnails` folder.

### To Reproduce
1. Have photos on an Android phone and connect via USB with MTP (PTP might be insanely broken depending on the lunar cycle and whether or not your cat has sneezed in the past day or so.)
2. Open Photos and select the device from the sidebar
3. Click on the "Import All" button
4. Photos should be imported, but thumbnails also get pulled in, as separate entities. This is particularly troublesome for images that have been removed from the Android device's library, but thumbnails are still present on the system.

### Expected behavior
Images from image/picture libraries should be imported, but excluding dot folders, particularly `.thumbnails`.

## Platform Information
![image](https://user-images.githubusercontent.com/58709504/74896989-e86b6f00-5352-11ea-8253-62f8d7e99275.png)
```
System:    Host: schy-ryze-hori Kernel: 5.5.2-050502-generic x86_64 bits: 64 gcc: 9.2.1
           Desktop: Gnome  (Gtk 3.22.30-1ubuntu4) Distro: elementary OS 5.1.2 Hera
Machine:   Device: desktop Mobo: ASUSTeK model: PRIME B350-PLUS v: Rev X.0x serial: N/A
           UEFI: American Megatrends v: 5407 date: 12/31/2019
CPU:       8 core AMD Ryzen 7 2700 Eight-Core (-MT-MCP-) arch: Zen rev.2 cache: 4096 KB
           flags: (lm nx sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm) bmips: 54398
           clock speeds: max: 3400 MHz 1: 1377 MHz 2: 1377 MHz 3: 1377 MHz 4: 1377 MHz 5: 1376 MHz 6: 1377 MHz
           7: 1377 MHz 8: 1377 MHz 9: 1377 MHz 10: 1377 MHz 11: 1377 MHz 12: 1377 MHz 13: 1377 MHz 14: 1377 MHz
           15: 1376 MHz 16: 1377 MHz
Graphics:  Card: Advanced Micro Devices [AMD/ATI] Device 731f bus-ID: 0c:00.0
           Display Server: x11 (X.Org 1.20.5 ) drivers: ati,amdgpu (unloaded: modesetting,fbdev,vesa,radeon)
           Resolution: 3840x1080@144.00hz
           OpenGL: renderer: AMD NAVI10 (DRM 3.36.0, 5.5.2-050502-generic, LLVM 9.0.0)
           version: 4.5 Mesa 19.2.8 Direct Render: Yes
Audio:     Card-1 Advanced Micro Devices [AMD] Family 17h (Models 00h-0fh) HD Audio Controller
           driver: snd_hda_intel bus-ID: 0e:00.3
           Card-2 Advanced Micro Devices [AMD/ATI] Device ab38 driver: snd_hda_intel bus-ID: 0c:00.1
           Card-3 Creative Labs Sound Core3D [Sound Blaster Recon3D / Z-Series]
           driver: snd_hda_intel bus-ID: 09:00.0
           Card-4 Logitech HD Pro Webcam C920 driver: USB Audio usb-ID: 003-006
           Card-5 C-Media driver: USB Audio usb-ID: 001-002
           Card-6 Kingston driver: USB Audio usb-ID: 001-005
           Sound: Advanced Linux Sound Architecture v: k5.5.2-050502-generic
Network:   Card: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller
           driver: r8169 port: f000 bus-ID: 04:00.0
           IF: enp4s0 state: up speed: 1000 Mbps duplex: full mac: <filter>
Drives:    HDD Total Size: 7251.4GB (4.9% used)
           ID-1: /dev/nvme0n1 model: Samsung_SSD_960_EVO_250GB size: 250.1GB
           ID-2: /dev/sda model: WDC_WDS500G2B0A size: 500.1GB temp: 26C
           ID-3: /dev/sdb model: WDC_WDS500G2B0A size: 500.1GB temp: 24C
           ID-4: /dev/sdc model: WDC_WDS500G2B0A size: 500.1GB temp: 24C
           ID-5: USB /dev/sdd model: easystore_2624 size: 5000.9GB temp: 0C
           ID-6: /dev/sde model: WDC_WDS500G2B0A size: 500.1GB temp: 25C
Partition: ID-1: / size: 228G used: 53G (25%) fs: ext4 dev: /dev/nvme0n1p4
RAID:      No RAID devices: /proc/mdstat, md_mod kernel module present
Sensors:   System Temperatures: cpu: No active sensors found. Have you configured your sensors yet? mobo: N/A
Info:      Processes: 479 Uptime: 16:25 Memory: 6313.9/32114.7MB Init: systemd runlevel: 5 Gcc sys: 7.4.0
           Client: Shell (fish) inxi: 2.3.56
```

- [x] I'm using the latest released stable version

**Comment by fabiozaramella** [comment] 2020-08-12 20:34
Closing this as it appears to be a duplicate of #483

**Closed by fabiozaramella** 2020-08-12 20:34 UTC
