### ISSUE TITLE
Basic Brush/Shape Editing

### ISSUE THREAD

**Issue by Fatih20** [elementary/photos#521] opened 2019-08-02 13:07 UTC
Everytime I want to add shapes/ brush to indicate or highlight something, I need to go edit them with Pinta, which is not exactly comfortable. It would be cool if eOS Photos app could add something basic. Just need width, color, and type of brush. That's it.

**Comment by peteruithoven** [comment] 2019-08-04 20:33
Thanks for the report! I'm afraid this is a duplicate of https://github.com/elementary/photos/issues/86

**Closed by peteruithoven** 2019-08-04 20:33 UTC
