### ISSUE TITLE
Photo information is unavailable when opening the image file directly

### ISSUE THREAD

**Issue by sprite-1** [elementary/photos#481] opened 2018-12-22 01:19 UTC
When I open a photo from the Photos app start page, it shows useful EXIF data on the right. However, when I open picture file directly from Files, it doesn't show that nor is there a way to show/hide that information.

**Comment by cassidyjames** [comment] 2020-01-04 04:06
Duplicate of #463

**Closed by cassidyjames** 2020-01-04 04:06 UTC
Labels: Priority: Low, Status: Confirmed
