### ISSUE TITLE
Empty settings window on current master branch

### ISSUE THREAD

**Issue by artemanufrij** [elementary/photos#192] opened 2017-11-02 18:23 UTC
![bildschirmfoto von 2017-11-02 19 22 46](https://user-images.githubusercontent.com/16517095/32343305-56a1afd8-c003-11e7-9e80-bee1a05a1455.png)

**Comment by davidmhewitt** [comment] 2017-11-02 19:18
Not empty settings window on current master branch:
![image](https://user-images.githubusercontent.com/3372394/32345593-967b2004-c002-11e7-8863-88692554f0f1.png)

Can you provide more information? Is there any terminal output? Did you install the branch or just run it from the build folder?

**Comment by artemanufrij** [comment] 2017-11-02 19:37
@davidmhewitt just run from builder folder.
./src/pantheon-photos -> open settings
```
[WARNING 20:36:25.488212] [GLib-GObject] invalid cast from 'Video' to 'Photo'
[WARNING 20:36:25.488260] [GLib-GObject] invalid cast from 'Video' to 'Photo'
[WARNING 20:36:25.488276] [GLib-GObject] invalid cast from 'Video' to 'Photo'
[WARNING 20:36:25.488292] [GLib-GObject] invalid cast from 'Video' to 'Photo'
[FATAL 20:36:28.488640] [Gtk] gtk_scrolled_window_add_with_viewport: assertion 'GTK_IS_SCROLLED_WINDOW (scrolled_window)' failed
[WARNING 20:36:28.488722] [GLib-GObject] invalid (NULL) pointer instance
[FATAL 20:36:28.488772] [GLib-GObject] g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
[FATAL 20:36:28.488836] [Gtk] gtk_widget_set_sensitive: assertion 'GTK_IS_WIDGET (widget)' failed
[FATAL 20:36:28.491568] [Gtk] gtk_stack_add_titled: assertion 'GTK_IS_WIDGET (child)' failed
[FATAL 20:36:28.491641] [Gtk] gtk_stack_add_titled: assertion 'GTK_IS_WIDGET (child)' failed
[WARNING 20:36:28.492501] [GLib-GObject] invalid (NULL) pointer instance
[FATAL 20:36:28.492556] [GLib-GObject] g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
[FATAL 20:36:28.492603] [Gtk] gtk_container_add: assertion 'GTK_IS_CONTAINER (container)' failed
[FATAL 20:36:28.493102] [Gtk] gtk_switch_set_active: assertion 'GTK_IS_SWITCH (sw)' failed
[FATAL 20:36:28.493377] [Gtk] gtk_switch_set_active: assertion 'GTK_IS_SWITCH (sw)' failed
[FATAL 20:36:28.493615] [Gtk] gtk_switch_set_active: assertion 'GTK_IS_SWITCH (sw)' failed
[FATAL 20:36:28.493750] [Gtk] gtk_combo_box_text_insert: assertion 'GTK_IS_COMBO_BOX_TEXT (combo_box)' failed
[FATAL 20:36:28.493837] [Gtk] gtk_combo_box_text_insert: assertion 'GTK_IS_COMBO_BOX_TEXT (combo_box)' failed
[FATAL 20:36:28.494112] [Gtk] gtk_combo_box_set_active: assertion 'GTK_IS_COMBO_BOX (combo_box)' failed
[WARNING 20:36:28.494189] [GLib-GObject] invalid (NULL) pointer instance
[FATAL 20:36:28.494264] [GLib-GObject] g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
[FATAL 20:36:28.494507] [Gtk] gtk_switch_set_active: assertion 'GTK_IS_SWITCH (sw)' failed
[FATAL 20:36:28.503110] [Gtk] gtk_file_chooser_set_current_folder: assertion 'GTK_IS_FILE_CHOOSER (chooser)' failed
[WARNING 20:36:28.536575] [GLib-GObject] invalid (NULL) pointer instance
[FATAL 20:36:28.536671] [GLib-GObject] g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
```

**Comment by davidmhewitt** [comment] 2017-11-06 21:00
I'm going to close this as this as there is nothing wrong with the current master branch and this is expected behavior due to the way the preferences window is written in a Glade UI file and the fact that the preferences window deals with plugins which are also separate to the main executable.

You'll find that a lot of applications which use plugins need installing to test them properly.

I will however raise a different issue to remind us that we need to remove all the Glade UI files and review the way plugins are loaded which should help with this issue in the future.

**Closed by davidmhewitt** 2017-11-06 21:00 UTC
Labels: Status: Incomplete
