### ISSUE TITLE
Group multiple events for 1 date

### ISSUE THREAD

**Issue by nielsvl95** [elementary/photos#628] opened 2021-07-30 13:22 UTC
## What Happened
All pictures are added in seperate events.

## Expected Behavior
Pictures from the same date should be grouped in 1 event

## Steps to Reproduce

1.Add photo library
2. Open folder
3. Look at multiple events for 1 date

## Platform Information

Elementary OS 6.0 Beta 2
Photos app version 2.7.1
![Schermafdruk van 2021-07-30 15-16-42](https://user-images.githubusercontent.com/66212886/127659164-b1f5213a-1a56-4466-9549-fbb1b9c9de62.png)

**Comment by jondale** [comment] 2021-09-04 03:24
I came here to report this same issue.  I installed shotwell to see if it has the same issue and it does not.

**Comment by jeremypw** [comment] 2021-09-04 17:44
I think the reason separate events are shown is so you can customise each event name by right clicking on it.  I would support, however, another level of (virtual) folder for each day analagous to those already given for each month.

**Comment by marco4mp** [comment] 2021-10-15 22:14
Hi! @jeremypw. I think it's a bug. Because, separating each photo of the same day into different folders, in my opinion, doesn't make sense.

**Example** 
I took 7 photos in August on two different days. 5 photos on Aug.22 and 2 photos on Aug.5.

**Shotwell:**
In August, it creates two folders (two different days) and separates the photos according to the day they were taken.

![Captura de pantalla de 2021-10-15 18 08 22](https://user-images.githubusercontent.com/52709674/137555327-1f4391db-8504-4e2d-8f43-4bbdc57578f9.png)

**elementary Photos:**
In August, it creates seven folders. One photo for each folder. 🤔
![Captura de pantalla de 2021-10-15 18 08 29](https://user-images.githubusercontent.com/52709674/137555339-72bd93ac-ac10-442e-8ca6-4ab1247deb71.png)

(Excuse my English, I try to do my best 😢)

**Comment by jeremypw** [comment] 2021-10-17 13:59
I just discovered there is a way to merge all the events on one day into a single event.

 - Open the month the events occur in
 - Select the events you want to merge in the events page
 - Secondary-click on the selection to get the context menu
 - Choose  "Merge Events"

You can split out events from a merged event by selecting them and choosing "New Event" from the context menu.

**Comment by marco4mp** [comment] 2021-11-20 16:58
Hi @jeremypw. I have new info!
I was wondering why this problem did not catch my attention before (elementary 5.1) since I do a lot of work with photos.
So I installed Elementary 5.1.7 on a virtual machine to check Photos.
And what I thought. Photos on elementary 5.1 have a different behavior, that is, the same as Shotwell.

In both versions I tried the same folder with pictures from three different dates.
![Captura de pantalla de 2021-11-20 13 01 53](https://user-images.githubusercontent.com/52709674/142733901-df4412ac-5878-4bb1-8e57-a9ddecb13e30.png)

**elementary 5.1.7 - Photos 2.7.0**

Clicking on the year folder:
![Photos Hera_Year](https://user-images.githubusercontent.com/52709674/142733928-4387f88f-b1fc-479b-bfdb-9e1aa19f7a37.png)

Clicking on the month folder:
![Photos Hera_Month](https://user-images.githubusercontent.com/52709674/142733939-d428bea5-50aa-4374-8563-1debc24d3c19.png)


**elementary 6 - Photos 2.7.3**

Clicking on the year folder:
![Photos Odin_Year](https://user-images.githubusercontent.com/52709674/142734048-2e74a336-628c-4379-ac05-7a82120a26fc.png)

Clicking on the month folder:
![Photos Odin_Month](https://user-images.githubusercontent.com/52709674/142734053-3f14482d-0d81-48c4-bdf4-06843b37c7a6.png)

**Comment by marco4mp** [comment] 2021-11-20 17:26
So, the current version of Photos (2.7.3) makes the mistake of using each picture as an event by itself.
An "event" should be a kind of "album" containing pictures taken on the same day (like Photos 2.7.0 or Shotwell).

**Comment by jeremypw** [comment] 2021-11-20 17:28
Hmm - I'll have to look at where that regression appeared - I assume it was not intentional.  If I can revert that regression this PR will not be necessary.

**Comment by jeremypw** [comment] 2021-11-20 17:38
The only possible relevant commit I found so far relates to replacing some deprecated code in the way photos were timestamped (unfortunately one of my PRs!)  I'll see if that is the culprit.

**Comment by jeremypw** [comment] 2021-11-20 18:06
Yeah, that's the culprit. Unfortunately, photos that are already imported will not be affected by simply reverting the change so I will have to find a way to have both the old and new timestamp give the same result.

**Comment by marco4mp** [comment] 2021-11-20 20:13
Thanks!

**Closed** 2021-11-22 07:43 UTC
Labels: Priority: Wishlist
