### ISSUE TITLE
Photos aren't cleared when arrowing to previous / next image

### ISSUE THREAD

**Issue by second-story** [elementary/photos#176] opened 2017-09-30 03:19 UTC
When using arrow keys to move forward or backward across photos in a given directory, the photo that's currently viewed isn't cleared from the viewing area.  Depending on the photo's size, this can leave numerous images superimposed over one another, as you can see here:

![eos-photos-overlay-error](https://user-images.githubusercontent.com/24594605/31041982-e1a01526-a563-11e7-9317-aa32396c6a69.jpg)

The expected behavior is for the previous photo to be cleared, and for only the current photo to be seen.  Having one or more overlapping photo distracts from properly viewing / editing the current photo.

**Comment by cassidyjames** [comment] 2017-09-30 19:01
This is a problem with your GTK+ stylesheet, and a duplicate of #160. Perhaps we should have a fallback in the elementary Stylesheet…

**Closed by cassidyjames** 2017-09-30 19:01 UTC
