### ISSUE TITLE
ftp photos

### ISSUE THREAD

**Issue by princeofguilty** [elementary/photos#190] opened 2017-10-23 20:15 UTC
i see that photos cant open any pictures in ftp, if it is because it needs read write, maybe if there's no solution for that why not to make it copy the picture to a tmp folder then show it?

**Comment by davidmhewitt** [comment] 2017-11-06 00:35
Thanks for reporting this.

It seems to be a duplicate of #122. I'll close this so we can track the bug in just one place.

**Closed by davidmhewitt** 2017-11-06 00:35 UTC
