### ISSUE TITLE
Info sidebar not usable when opening image directly

### ISSUE THREAD

**Issue by cristianofmc** [elementary/photos#463] opened 2018-10-26 01:57 UTC
I tried to search and I could not, I think it's something quite simple and very useful.

**Comment by marco4mp** [comment] 2019-12-21 04:51
Maybe it refers to [(https://github.com/elementary/photos/issues/481#issue-393630362)](url)

**Comment by marco4mp** [comment] 2019-12-21 04:53
Maybe it refers to [https://github.com/elementary/photos/issues/481](url)

**Comment by marco4mp** [comment] 2019-12-21 04:56
Maybe it refers to [https://github.com/elementary/photos/issues/481]

**Comment by cassidyjames** [comment] 2020-01-04 04:06
@marco4mp ah you're probably right. I'll close that as a duplicate of this and add details.

**Comment by danrabbit** [comment] 2020-01-07 02:33
This seems to be a duplicate of #277

**Closed by danrabbit** 2020-01-07 02:33 UTC
Labels: Priority: Low, Status: Confirmed
