### ISSUE TITLE
Cannot pan with scrolling

### ISSUE THREAD

**Issue by bksubhuti** [elementary/photos#147] opened 2017-04-28 10:43 UTC
To do a "pan" while in zoom mode, I need to physically click the touch pad (which has no buttons).
It is better if two or three finger panning were to panning were to work.  (NOTE:  eog works in the same way (need to click..two finger is zoom control, but that does not mean .)

**Comment by cassidyjames** [comment] 2017-04-28 18:38
@bksubhuti I updated the title, but I can confirm the issue. Right now panning requires click-dragging instead of normal scroll events.

**Comment by cassidyjames** [comment] 2017-04-28 18:39
Ah wait, is this a duplicate of #142?

**Comment by davidmhewitt** [comment] 2017-10-11 23:44
No response from OP, but I'd say it sounds like a duplicate of #142 , so closing.

**Closed by davidmhewitt** 2017-10-11 23:44 UTC
Labels: Status: Confirmed
