### ISSUE TITLE
Photos app should have Dark theme by default.

### ISSUE THREAD

**Issue by uncertainquark** [elementary/photos#150] opened 2017-05-19 16:54 UTC
The Photo viewer is already fully dark themed. So is the videos app. It would be visually more consistent to have the Photos app fully dark too.

Here's how it looks now:
![screenshot from 2017-05-19 22-22-51](https://cloud.githubusercontent.com/assets/22585732/26258305/9eda11ec-3cb3-11e7-837c-49ca68ec8111.png)

And here is how it can look with a full dark theme:
![screenshot from 2017-05-19 22-19-30](https://cloud.githubusercontent.com/assets/22585732/26258323/b813bd16-3cb3-11e7-861b-00bb97737aa5.png)

Wouldn't it make sense to have the Photos app fully dark instead of the current semi dark?

**Comment by danrabbit** [comment] 2017-05-19 16:55
Closing as a duplicate of #31 

Please remember to search the tracker before reporting an issue to make sure your report is not a duplicate

**Closed by danrabbit** 2017-05-19 16:55 UTC
